import 'translation_keys.dart' as translation;

class En {
  Map<String, String> get translations => {
        translation.appName: 'MorphZing',
        translation.english: 'English',
        translation.spanish: 'Spanish',
        translation.setupLanguageDescription:
            '''Control your life's journey all\n in one place''',
        translation.next: 'Next',
        translation.useYourJournalTo: 'Use your journal to',
        translation.trackYourProgress: 'Track your progress',
        translation.findInspiration: 'Find inspiration',
        translation.gainSelfConfidence: 'Gain self-confidence',
        translation.strengthenMemory: 'Strengthen memory',
        translation.writeDownYourGoals: 'Write down your goals',
        translation.trackYourGrowth: 'Track your growth',
        translation.improveWritingCommunicationSkills:
            'Improve writing and communication skills',
        translation.organize: 'Organize',
        translation.share: 'Share',
        translation.invite: 'Invite',
        translation.timeManagement: 'Time Management',
        translation.getStarted: 'Get Started',
        translation.login: 'Log in',
        translation.forgotPassword: 'Forgot password?',
        translation.phone: 'Phone number',
        translation.emailOrPhone: 'E-mail or phone number',
        translation.password: 'Password',
        translation.doNotHaveAnAccountYet: '''Don't have an account yet?''',
        translation.signUp: 'Sign up',
        translation.orLogInWith: 'Or Log in with',
        translation.recoveryPassword: 'Recovery password',
        translation.recoveryPasswordDesc:
            'Please enter your phone number and we will send you verification code',
        translation.continueKey: 'Continue',
        translation.verification: 'Verification',
        translation.pleaseEnterTheCode:
            'Please enter the code that we\'ve sent to',
        translation.changePhoneNumber: 'Change phone number',
        translation.codeVerification: 'Code verification',
        translation.resetPassword: 'Reset password',
        translation.newPassword: 'New password',
        translation.confirmPassword: 'Confirm password',
        translation.alreadyHaveAnAccount: 'Already have an account?',
        translation.orSignUpWith: 'Or sign up with',
        translation.byUsingMorphzingYouAgreeToThe:
            'By using Morphzing you agree to the',
        translation.termsOfUse: 'Terms of Use',
        translation.privacyPolicy: 'Privacy Policy',
        translation.createPassword: 'Create password',
        translation.passwordDoesNotMatch: 'Password doesn\'t match!',
        translation.passwordLengthMustBeAt:
            'Password length must be at least 8 characters!',
        translation.camera: 'Camera',
        translation.gallery: 'Gallery',
        translation.whatIsYourFio: 'What is your full name',
        translation.whatIsYourBio: 'What is your bio',
        translation.aboutMe: 'About me',
        translation.bio: 'Bio',
        translation.pleaseEnterYourBirthDate: 'Please enter your birthday date',
        translation.pleaseEnterYourEmail: 'Please enter your email',
        translation.email: 'Email',
        translation.howDoYouIdentity: 'How do you identify',
        translation.save: 'Save',
        translation.male: 'Male',
        translation.female: 'Female',
        translation.nonBinary: 'Non binary',
        translation.pleaseSelect: 'Please select',
        translation.yourPasswordHasBeenSuccessfullyChanged:
            'Your password has been successfully changed',
        translation.great: 'Great',
        translation.home: 'Home',
        translation.agenda: 'Agenda',
        translation.calendar: 'Calendar',
        translation.journal: 'Journal',
        translation.zingPhotography: 'Zing Photography',
        translation.worldChangers: 'World Changers',
        translation.chat: 'Chat',
        translation.todo: 'To do',
        translation.todoCapital: 'To Do',
        translation.today: 'Today',
        translation.monthly: 'Monthly',
        translation.yearly: 'Yearly',
        translation.task: 'task',
        translation.tasks: 'tasks',
        translation.capitalTask: 'Task',
        translation.capitalTasks: 'Tasks',
        translation.all: 'All',
        translation.goals: 'Goals',
        translation.done: 'Done',
        translation.noTasksYet: '''You don't have any tasks yet''',
        translation.taskName: 'Task name',
        translation.dateTime: 'Date & Time',
        translation.pleaseEnterDateTime: 'Please enter Date & Time',
        translation.description: 'Description',
        translation.pleaseEnterDescription: 'Please enter description',
        translation.goal: 'Goal',
        translation.hours: 'hour (s)',
        translation.minutes: 'minutes',
        translation.beforeStart: 'before start',
        translation.cancel: 'Cancel',
        translation.reminder: 'Reminder',
        translation.create: 'Create',
        translation.month: 'Month',
        translation.pleaseEnterMonth: 'Please enter the following Month',
        translation.sendSmsMessageOnTheFirstDay:
            'Send SMS message on the 1st day of the month',
        translation.months: 'Months',
        translation.year: 'Year',
        translation.pleaseEnterYear: 'Please enter Year',
        translation.sendSmsEveryThreeMonths: 'Send SMS message every 3 months',
        translation.event: 'event',
        translation.events: 'events',
        translation.capitalEvent: 'Event',
        translation.capitalEvents: 'Events',
        translation.noEventsYet: '''You don't have any events yet''',
        translation.eventName: 'Event name',
        translation.startFinishDate: 'Start and Finish date',
        translation.selectStartEndTime: 'Select start and end time',
        translation.selectInvitees: 'Select invitees',
        translation.place: 'Place',
        translation.selectAddress: 'Select the address',
        translation.repeat: 'Repeat',
        translation.doNotRepeat: '''Don't repeat''',
        translation.startTime: 'Start time',
        translation.finishTime: 'Finish time',
        translation.inviteUpTo: 'Invite up to',
        translation.participants: 'participants',
        translation.searchByName: 'Search by name',
        translation.submit: 'Submit',
        translation.everyday: 'Everyday',
        translation.everyWeek: 'Every week',
        translation.everyMonth: 'Every month',
        translation.everyYear: 'Every year',
        translation.noInviteesAdded: 'No invitees added',
        translation.addPhotoFromGallery: 'Add photos from gallery',
        translation.pictures: 'Pictures',
        translation.noPicturesAdded: 'No pictures were uploaded',
        translation.noTasksForToday: 'No Tasks for Today',
        translation.noEventsForToday: 'No Events for Today',
        translation.subscription: 'Subscription',
        translation.subscriptionPlan: 'Subscription plan',
        translation.subscriptionNotActive: 'Subscription is not active',
        translation.subscriptionActive: 'Subscription activated',
        translation.willBeDebitedOn: 'will be debited on',
        translation.mySubscriptionPlan: 'My subscription plan',
        translation.freeDescription:
            'Enjoy arranging your day with the MorphZing Free subscription plan.',
        translation.basicDescription:
            'Get the benefits and enjoy arranging your day with the MorphZing Basic subscription plan.',
        translation.basicDialogDescription:
            'Get all the benefits at once and enjoy the freedom of arranging your day!',
        translation.premiumDescription:
            'Get all the benefits at once and enjoy creating unlimited tasks/events/and journal notes with the MorphZing Premium subscription plan.',
        translation.subscribeForMoreFeatures: 'Subscribe for more features',
        translation.changeSubscriptionPlan: 'Change the subscription plan',
        translation.cancelSubscription: 'Cancel subscription',
        translation.manageSubscription: 'Manage subscription',
        translation.cancelSubscriptionDescription:
            'Are you sure you want to cancel? Cancelling will delete all of your data and it will not be recoverable.',
        translation.howtoCancelSubscription:
            'You can manage your subscriptions on your @account account under subscriptions',
        translation.templates: 'Background',
        translation.standardView: 'Standard view',
        translation.hourMinute: 'Hour and minute',
        translation.monthDayYear: 'Month day and year',
        translation.journeyTitle: 'Title of journey',
        translation.journeyDescription:
            'Description of journey, e.g., I traveled to France and saw a lot of beautiful places. France has a big history and The Eiffel Tower is one of the world`s wonders of the world',
        translation.pendingInvitations: 'Pending invitations',
        translation.noEvents: 'No events',
        translation.noPendingEvents: 'No pending events',
        translation.date: 'Date',
        translation.notSpecified: 'Not specified',
        translation.notes: 'Notes',
        translation.notProvided: 'Not provided',
        translation.accept: 'Accept',
        translation.acceptThisEvent:
            'Are you sure you want to accept this event?',
        translation.decline: 'Decline',
        translation.declineThisEvent:
            'Are you sure you want to decline this event?',
        translation.no: 'No',
        translation.yes: 'Yes',
        translation.ownSelfCare: 'Own Self-care',
        translation.suggestions: 'Suggestions',
        translation.noSuggestionsForThisDay: 'No suggestions for this day',
        translation.couldNotLaunchUrl: 'Could not launch current url',
        translation.eventCreated: 'Event created successfully',
        translation.eventCreateFailed: 'Failed to create event',
        translation.eventEdited: 'Event edited successfully',
        translation.eventEditFailed: 'Failed to edit the event',
        translation.eventStatusChanged: 'Event status changed successfully',
        translation.eventStatusFailed: 'Failed to change the event status',
        translation.participantAddFailed:
            'Failed to add participants to an event',
        translation.participantChangeFailed:
            'Failed to change participants of the event',
        translation.eventDeleted: 'Event deleted successfully',
        translation.eventDeleteFailed: 'Failed to delete event',
        translation.imageUploadFailed: 'Images uploading failed',
        translation.taskStatusFailed: 'Failed to change task status',
        translation.deleteTask: 'Delete task?',
        translation.deleteEvent: 'Delete event?',
        translation.taskCreated: 'Task created successfully',
        translation.taskEdited: 'Task edited successfully',
        translation.taskDeleted: 'Task deleted successfully',
        translation.completeTask: 'Complete task?',
        translation.completeEvent: 'Complete event?',
        translation.startCannotBeEarlier:
            'Start time cannot be earlier than current time',
        translation.chooseDifferentTime: 'Please, choose different time',
        translation.noReminderSet: 'No reminder is set',
        translation.allFieldsRequired: 'All fields are required',
        translation.startDateCannotBeEarlier:
            'Start date cannot be earlier than current date',
        translation.chooseDifferentDate: 'Please, choose different date',
        translation.taskCreatedForThisDay:
            'A task is created for this day. Please check the "Today" task.',
        translation.onlyUpTo: 'Only up to',
        translation.photosAreAllowed: 'photos are allowed',
        translation.permissionToGallery:
            'App needs permission to show all your gallery photos for you to choose, which ones to upload, please go to settings and give permission to photos(gallery)',
        translation.openSettings: 'Open settings',
        translation.upload: 'Upload',
        translation.eventStatusAlreadyChanged:
            'Status of the event already changed',
        translation.noStartTimeSpecified: 'No start time specified',
        translation.permissionPermanentlyDenied:
            'Permission is permanently denied',
        translation.contactPermissionManual:
            'Please go to settings and give permission to contacts manually',
        translation.travelPicturesFailed: 'Failed to get travel pictures',
        translation.inviteesAreAllowed: 'invitees are allowed',
        translation.morphzingWouldAccessContacts:
            'MorhpZing would like to access your contacts',
        translation.chooseWhomToInvite:
            'Choose whom to invite to your events from your contact list. Invited contacts information will be sent to and used in the server',
        translation.forever: 'Forever',
        translation.until: 'Until',
        translation.duration: 'Duration',
        translation.oneDayOfWeek: 'At least one day of week must be chosen',
        translation.startEarlierEnd: 'Start time must be earlier than end time',
        translation.eventNameDateRequired: 'Event name and date are required',
        translation.inviteAccepted: 'Invitation accepted',
        translation.premiumTemplate: 'premium background',
        translation.journalsPerMonth: 'Journals entries per month',
        translation.photosToUpload: 'Photos to upload',
        translation.freePremiumTemplates: 'free premium background',
        translation.freePremiumTemplate: 'free premium background',
        translation.currentPlan: 'Current plan',
        translation.noSubProducts: 'No subscription products',
        translation.learnMore: 'Learn more',
        translation.unlimited: 'Unlimited',
        translation.fetchOfferingFail:
            'Something went wrong while fetching offerings',
        translation.purchaseTemplateFail: 'Failed to purchase a background',
        translation.freeTemplate: 'free background',
        translation.noTemplatesToShow: 'No background to show',
        translation.notificationSettings: 'Notification settings',
        translation.preferReceiveNotification:
            'Would you like to be reminded to journal every day?',
        translation.notifyMe:
            '''Notify me if I don't create a post every day''',
        translation.smsMessage: 'SMS message',
        translation.error: 'Error',
        translation.success: 'Success',
        translation.attention: 'Attention',
        translation.reminderBeforeStart: 'Reminder before start',
        translation.todayJourney: 'Today\'s Journey',
        translation.myLifeJourney: 'My Life Journey',
        translation.totalEntries: 'Total Entries',
        translation.currentStreak: 'Current Streak',
        translation.weeksJournaling: 'Weeks Journaling',
        translation.noJourneyForTodayTitle: 'No Journey for today',
        translation.noJourneyForTodayDesc:
            '''You don't have Journey for today, don't forget to record interesting moments in your life, you can start right now''',
        translation.journey: 'Journey',
        translation.titleName: 'Title Name',
        translation.descriptions: 'Descriptions',
        translation.textFieldOrAddLink: 'Text Field Or Add Link',
        translation.photos: 'Photos',
        translation.photo: 'Photo',
        translation.options: 'Options',
        translation.deleteNote: 'Delete note',
        translation.deleteJourney: 'Delete journey',
        translation.deletePhotos: 'Delete photos',
        translation.profile: 'Profile',
        translation.fullName: 'Full name',
        translation.enterYourName: 'Enter your name',
        translation.birthDate: 'Birth date',
        translation.setYourPhone: 'Set your phone number',
        translation.cannotChangeEmail: '''You can't change an email''',
        translation.setYourEmail: 'Set your email',
        translation.enterPassword: 'Please enter your password',
        translation.appLanguage: 'Application language',
        translation.deleteAccPermanently:
            'Are you sure you want to delete the account permanently?',
        translation.dataWillBeDeleted:
            'Please note that all data will be deleted',
        translation.delete: 'Delete',
        translation.deleteAccount: 'Delete account',
        translation.youChangingWorld: 'You are changing the world!',
        translation.yourMembershipSupport:
            'Your membership helps to support the following foundations:',
        translation.youMakeDifference: 'Thank you! You make a difference!',
        translation.missionStatement: 'Mission statement',
        translation.aboutTheApp: 'About the app',
        translation.ourMission: 'Our Mission',
        translation.ourMissionDescription:
            'To help humanity achieve and fulfill their Personal Legend/Journey with a balanced life full of positive energy and hope to make our earth a better place.',
        translation.balanceEnergyHopeEarth: 'Balance.Energy.Hope.Earth',
        translation.faq: 'FAQ',
        translation.disclaimer: 'Disclaimer',
        translation.deletePhoto: 'Delete photo',
        translation.media: 'Media',
        translation.location: 'Location',
        translation.weblink: 'Weblink',
        translation.weblinkDescription: 'Add weblink',
        translation.document: 'Document',
        translation.every: 'Every',
        translation.weeks: 'week(s)',
        translation.misc: 'Misc',
        translation.failedFetchHomeBanner:
            'Could not fetch home page banner image',
        translation.failedUploadHomeBanner:
            'Could not upload home page banner image',
        translation.oldPassword: 'Old password',
        translation.newPhoneNumber: 'New phone number',
        translation.whatIsYourNewPhoneNumber: 'What is your new phone number?',
        translation.yourPhoneHasBeenSuccessfullyChanged:
            'Your phone has been successfully changed',
        translation.noInternetTitle: 'No internet access',
        translation.noInternetDesc: 'Try connecting to the Internet or WiFi',
        translation.swipeToLeftToDelete: '(swipe to left to delete)',
        translation.changePassword: 'Change password',
        translation.restorePurchase: 'Restore purchase',
        translation.mo: 'mo',
        translation.changePasswordErrorMessage: 'Password is incorrect',
        translation.subscriptionIncludes: 'Subscription includes:',
        translation.notesPerMonth: 'Notes per month',
        translation.tasksAndTodos: 'Tasks, To-Do lists and Goal setting',
        translation.eventsPerMonth: 'Events in your agenda per month',
        translation.uploadPhotosInAll:
            'In app photo uploads that can be used in Agenda or Journal',
        translation.freeBasicTemplates: 'Free basic backgrounds',
        translation.plus: 'plus',
        translation.premiumTemplates: 'premium backgrounds',
        translation.allSubscriptionHeader:
            'Morph your future into something amaZing',
        translation.more: '< more >',
        translation.thisWillBeYour: 'This will be your ',
        translation.journeyCreateSuccessMessage: 'Journey created successfully',
        translation.journeyEditedSuccessMessage: 'Journey edited successfully',
        translation.journeyDeleteMessage: 'Journey deleted successfully',
        translation.noteCreateSuccessMessage: 'Note created successfully',
        translation.noteEditedSuccessMessage: 'Note edited successfully',
        translation.noteDeleteMessage: 'Note deleted successfully',
        translation.areYouSureWantToExitNote:
            'Are you sure you want to exit?\nAll unsaved information will be lost.',
        translation.twilioSmsConsent:
            'I agree to receive messages from MorphZing at the phone number provided above',
        translation.easycheckoff: "Easily check off completed tasks",
        translation.setandtrackyourgoals: 'Set and track your goals',
        translation.seealltasksweeklycalendar:
            'See all tasks in your weekly calendar',
        translation.reminderstocompletegoal: 'Reminders to complete goal',
        translation.agendawithcolorcodedcalendar:
            'Agenda with Color-Coded Calendar',
        translation.selfcarecalendartips: 'Self-Care Calendar Tips',
        translation.seealltasksinmonthlycalendar:
            'See all tasks in your monthly calendar',
        translation.smartInvitesTextEventInvitationsFromYourCalendar:
            'Smart Invites: Text Event Invitations from Your Calendar',
        translation.textToConfirmOrDeclineEvents:
            'Text to Confirm or Decline Events',
        translation.remindersViaText: 'Reminders via Text',
        translation.addColorCodedEventsFromCalendarView:
            'Add Color-Coded Events from Calendar View',
        translation.shortcutInstantToDoAndEventCalendar:
            'Shortcut: Instant To-Do and Event Calendar',
        translation.easyScrollMyLifeJourneyJournalEntries:
            'Easy Scroll: My Life Journey Journal Entries',
        translation.trackYourJourneyWithTotalEntriesCount:
            'Track Your Journey with \"total entries\" count',
        translation.unleashYourCompetitiveStreak:
            'Unleash Your Competitive Streak',
        translation.trackYourWeeksOfJournalingProgress:
            'Track Your Weeks of Journaling Progress',
        translation.divideEachJournalEntryIntoSections:
            'Divide Each Journal Entry into Sections',
        translation.editYourJournalEntriesWithEase:
            'Edit Your Journal Entries with Ease',
        translation.automaticDateTime: 'automatic date/time',
        translation.titleYourJournalEntries: 'Title Your Journal Entries',
        translation.unlimitedJournalingSpace: 'Unlimited Journaling Spaces',
        translation.monthlyJournalViewTrackYourJournalingDaysAtAGlance:
            'Monthly Journal View: Track Your Journaling Days at a Glance',
        translation.monthlyJournalViewWithSummaryAtAGlance:
            'Monthly Journal View with Summary at a Glance',
        translation.pickYourProfilePictureFromOurLibrary:
            'Pick your Your Profile Picture from our library',
        translation.englishSpanishFeatureSeamlessLanguageSwitching:
            'English-Spanish Feature: Seamless Language Switching',
        translation.zingPhotographyElevateYourSpaceWithStyleAndGrace:
            'Zing Photography: Elevate your Space with Style and Grace',
        translation.joinOurPhilanthropistMovementAndMakeADifferenceTogether:
            'Join Our Philanthropist Movement and Make a Difference Together',
        translation.oneStopShopForYourSocialMediaConnection:
            'One Stop shop for your Social Media connection',
        translation.easytousecolorcodedcalendar:
            'Easy-to-Use Color-Coded Calendar',
        translation.customizeyourprofilepicturewithease:
            'Customize Your Profile Picture with Ease',
        translation.abiitytocheckcomplete: 'Abiity to check complete',
        translation.seealltasksinyouryearlycalendar:
            'See all tasks in your yearly calendar',
        translation.travelagendawithphotouploads:
            'Travel Agenda with Photo Uploads',
        translation.recordyourjournalentrieswithyourvoice:
            'Record Your Journal Entries with Your Voice',
        translation.organizedetailswitheasynotecreation:
            'Organize Details with Easy Note Creation',
        translation.organizenotesintocustomfolders:
            'Organize Notes into Custom Folders',
        translation.rsvpmadeasy:
            'RSVP Made Easy: Never Forget to Respond Again',
        translation.morphzingbetterwithpremiumplans:
            'MorphZing Better With Premium Plans',
        translation.premiumcarddescription:
            'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying',
        translation.letsgopremium: 'Let’s Go Premium!',
        translation.myAccount: 'My Account',
        translation.logout: 'Log out',
        translation.premiumLiteText:
            'Don’t Go Breaking Our Hearts — give us another chance. Stick Around for Just \$3.99/ Next Month!',
        translation.subscribeNow: 'Subscribe now',
        translation.continuewithmorphzingbasic: 'Continue with Morphzing Basic',
        translation.continuewithmorphzingfree: 'Continue with Morphzing Free',
        translation.oneMonthfreeMonthTrial:
            'Please enjoy 30 Days of Premium Features and enjoy the start of your new journey!',
        translation.freetrialperiodactive: 'Welcome to the family!',
        translation.yoursubscriptionformorphZingpremiumliteendingsoon:
            'Your subscription for MorphZing Premium Lite is ending soon!',
        translation.freetrialExpired:
            'Your trial’s ending, don’t say goodbye! Your journey’s just beginning, let’s keep going.',
        translation.subscriptionExpired: 'The subscription has expired.',
        translation.premiumLiteTextHeader: 'Stay and Save!',
        translation.keepItAll: 'Keep it all!',
        translation.threeNineNineNextMonth: '\$3.99 Next Month',
        translation.enjoyTheChange:
            'Enjoy the change - we\'ve got you covered!',
        translation.specialOfferEndingSoon:
            'Your Special Offer is Ending Soon!',
        translation.thanksForGivingUsTry: 'Thanks for giving us a try.',
        translation.fiveJournalingSpace: '5 journaling spaces',
        translation.twentyfiveJournalingSpace: '25 journaling spaces',
        'theme': 'Theme',
        'themeSettings': 'Theme Settings',
        'system': 'System',
        'light': 'Light',
        'dark': 'Dark',
        'followPhoneSettings': 'Follow phone settings',
        'alwaysLightTheme': 'Always light theme',
        'alwaysDarkTheme': 'Always dark theme',
      };
}
